server:
  port: 8898


spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/react
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: globepoint!
  
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK